version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jboss.weld:weld-core-bom
    versions:
    - 4.0.0.Final
    - 4.0.1.Final
